name: Legends Golf Tour
favicon: null
layout_spectrum: 0.506656899349764
typography_spectrum: 0.12674516602419317
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.25261022825725377
  lightness: 0.5797002166509628
  saturation: 0.00019138935022056103
  rhythmicContrast: 0.46088139130733907
purpose: []
